# Generated by Django 5.1.2 on 2024-12-22 13:01

import datetime
import django.db.models.deletion
import mainapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Consultant",
            fields=[
                (
                    "consultant_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("headline", models.CharField(max_length=150)),
                ("about", models.CharField(blank=True, max_length=500, null=True)),
                ("services", models.JSONField(blank=True, default=list, null=True)),
                (
                    "hourly_rate",
                    models.CharField(blank=True, default="0", max_length=30, null=True),
                ),
                ("education", models.JSONField(blank=True, null=True)),
                ("certificates_licenses", models.JSONField(blank=True, null=True)),
                ("skills", models.JSONField(blank=True, null=True)),
                ("experiences", models.JSONField(blank=True, null=True)),
                ("website", models.CharField(blank=True, max_length=30, null=True)),
                ("country", models.CharField(blank=True, max_length=20, null=True)),
                ("city", models.CharField(blank=True, max_length=20, null=True)),
                ("area", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="consultants/photos/"
                    ),
                ),
                ("gender", models.CharField(blank=True, max_length=20, null=True)),
                ("dob", models.CharField(blank=True, max_length=30, null=True)),
                ("saved_jobs", models.JSONField(blank=True, null=True)),
                (
                    "credit",
                    models.CharField(blank=True, default="0", max_length=20, null=True),
                ),
                (
                    "active_package",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("block_credit", models.BooleanField(default=False)),
                ("is_consultant_verified", models.BooleanField(default=False)),
                ("availability_status", models.BooleanField(default=True)),
                (
                    "available_days",
                    models.JSONField(
                        blank=True,
                        default=mainapp.models.get_default_availability,
                        null=True,
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        choices=[
                            ("-12", "UTC-12"),
                            ("-11", "UTC-11"),
                            ("-10", "UTC-10"),
                            ("-9", "UTC-9"),
                            ("-8", "UTC-8"),
                            ("-7", "UTC-7"),
                            ("-6", "UTC-6"),
                            ("-5", "UTC-5"),
                            ("-4", "UTC-4"),
                            ("-3", "UTC-3"),
                            ("-2", "UTC-2"),
                            ("-1", "UTC-1"),
                            ("0", "UTC"),
                            ("1", "UTC+1"),
                            ("2", "UTC+2"),
                            ("3", "UTC+3"),
                            ("4", "UTC+4"),
                            ("5", "UTC+5"),
                            ("6", "UTC+6"),
                            ("7", "UTC+7"),
                            ("8", "UTC+8"),
                            ("9", "UTC+9"),
                            ("10", "UTC+10"),
                            ("11", "UTC+11"),
                            ("12", "UTC+12"),
                        ],
                        default="0",
                        max_length=10,
                    ),
                ),
                (
                    "systemdate",
                    models.DateTimeField(
                        blank=True, default=datetime.datetime.now, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Employer",
            fields=[
                ("employer_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "company_website",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("designation", models.CharField(blank=True, max_length=30, null=True)),
                ("department", models.CharField(blank=True, max_length=30, null=True)),
                ("headline", models.CharField(blank=True, max_length=150, null=True)),
                ("about", models.CharField(blank=True, max_length=500, null=True)),
                ("education", models.JSONField(blank=True, default=list, null=True)),
                (
                    "certificates_licenses",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                ("skills", models.JSONField(blank=True, default=list)),
                ("experiences", models.JSONField(blank=True, default=list, null=True)),
                ("website", models.CharField(blank=True, max_length=30, null=True)),
                ("country", models.CharField(blank=True, max_length=20, null=True)),
                ("city", models.CharField(blank=True, max_length=20, null=True)),
                ("area", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "photo",
                    models.FileField(
                        blank=True, null=True, upload_to="employer_photos/"
                    ),
                ),
                ("gender", models.CharField(blank=True, max_length=20, null=True)),
                ("dob", models.CharField(blank=True, max_length=30, null=True)),
                ("saved_jobs", models.JSONField(blank=True, default=list, null=True)),
                ("credit", models.CharField(blank=True, default="0", max_length=30)),
                (
                    "active_package",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "block_credit",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "is_employer_verified",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "systemdate",
                    models.DateTimeField(
                        blank=True, default=datetime.datetime.now, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Package",
            fields=[
                ("package_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=200)),
                ("price", models.CharField(max_length=50)),
                ("duration_days", models.CharField(max_length=50)),
                (
                    "target_role",
                    models.CharField(
                        choices=[
                            ("talent", "Talent"),
                            ("employer", "Employer"),
                            ("consultant", "Consultant"),
                            ("admin", "Admin"),
                        ],
                        max_length=30,
                    ),
                ),
                ("features", models.JSONField(blank=True, default=list, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "systemdate",
                    models.DateTimeField(
                        blank=True, default=datetime.datetime.now, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Talent",
            fields=[
                ("talent_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("headline", models.CharField(blank=True, max_length=150, null=True)),
                ("about", models.CharField(blank=True, max_length=500, null=True)),
                ("education", models.JSONField(blank=True, default=list, null=True)),
                (
                    "certificates_licenses",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                ("skills", models.JSONField(blank=True, default=list)),
                ("experiences", models.JSONField(blank=True, default=list, null=True)),
                (
                    "resume",
                    models.FileField(blank=True, null=True, upload_to="resumes/"),
                ),
                (
                    "cover_letter",
                    models.FileField(blank=True, null=True, upload_to="cover_letters/"),
                ),
                ("website", models.CharField(blank=True, max_length=30, null=True)),
                ("country", models.CharField(blank=True, max_length=20, null=True)),
                ("city", models.CharField(blank=True, max_length=20, null=True)),
                ("area", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="photos/"),
                ),
                (
                    "open_to_work",
                    models.BooleanField(blank=True, default=True, null=True),
                ),
                ("gender", models.CharField(blank=True, max_length=20, null=True)),
                ("dob", models.CharField(blank=True, max_length=30, null=True)),
                ("saved_jobs", models.JSONField(blank=True, default=list)),
                (
                    "current_salary",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "expected_salary",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "credit",
                    models.CharField(blank=True, default="0", max_length=20, null=True),
                ),
                (
                    "block_credit",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "active_package",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "systemdate",
                    models.DateTimeField(
                        blank=True, default=datetime.datetime.now, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "testimonial_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("user_id", models.UUIDField()),
                ("rating", models.FloatField()),
                ("headline", models.CharField(max_length=100)),
                ("comment", models.CharField(max_length=100)),
                ("review_date", models.DateTimeField()),
                (
                    "systemdate",
                    models.DateTimeField(
                        blank=True, default=datetime.datetime.now, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=30, unique=True)),
                ("username", models.CharField(max_length=30, unique=True)),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
                ("password_hash", models.CharField(max_length=70)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("talent", "Talent"),
                            ("employer", "Employer"),
                            ("consultant", "Consultant"),
                            ("admin", "Admin"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "systemdate",
                    models.DateTimeField(
                        blank=True, default=datetime.datetime.now, null=True
                    ),
                ),
                (
                    "account_status",
                    models.CharField(
                        choices=[
                            ("unverified", "Unverified"),
                            ("verified", "Verified"),
                            ("blocked", "Blocked"),
                        ],
                        default="unverified",
                        max_length=15,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobPosting",
            fields=[
                ("job_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=200)),
                (
                    "vacancy_count",
                    models.CharField(blank=True, default="1", max_length=30, null=True),
                ),
                ("benefits", models.JSONField(blank=True, default=list, null=True)),
                (
                    "responsibilities",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                (
                    "education_requirements",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("featured", models.BooleanField(default=False)),
                (
                    "language_requirements",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                (
                    "application_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("easy_apply", "Easy Apply"),
                            ("link_apply", "Link Apply"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "application_link",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "application_instruction",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("industry", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "skills_required",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                (
                    "salary_range",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("country", models.CharField(blank=True, max_length=30, null=True)),
                ("city", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "job_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Contract", "Contract"),
                            ("Freelance", "Freelance"),
                            ("Full Time", "Full Time"),
                            ("Internship", "Internship"),
                            ("Part Time", "Part Time"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Fresh", "Fresh"),
                            ("Less Than 1 Year", "Less Than 1 Year"),
                            ("1 Year", "1 Year"),
                            ("2 Years", "2 Years"),
                            ("3 Years", "3 Years"),
                            ("4 Years", "4 Years"),
                            ("5 Years", "5 Years"),
                            ("6 Years", "6 Years"),
                            ("7 Years", "7 Years"),
                            ("8 Years", "8 Years"),
                            ("9 Years", "9 Years"),
                            ("10 Years", "10 Years"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "location_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("remote", "Remote"),
                            ("on-site", "On-Site"),
                            ("hybrid", "Hybrid"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_open", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            ("Published", "Published"),
                            ("Archived", "Archived"),
                        ],
                        default="Draft",
                        max_length=20,
                    ),
                ),
                ("views", models.PositiveIntegerField(default=0)),
                ("tags", models.JSONField(blank=True, default=list, null=True)),
                (
                    "systemdate",
                    models.DateTimeField(
                        blank=True, default=datetime.datetime.now, null=True
                    ),
                ),
                (
                    "employer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainapp.employer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "job_application_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("short-listed", "Short-Listed"),
                            ("interviewing", "Interviewing"),
                            ("hired", "Hired"),
                            ("expired", "Expired"),
                        ],
                        default="applied",
                        max_length=20,
                    ),
                ),
                ("application_date", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("feedback", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "application_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "systemdate",
                    models.DateTimeField(
                        blank=True, default=datetime.datetime.now, null=True
                    ),
                ),
                (
                    "job_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="mainapp.jobposting",
                    ),
                ),
                (
                    "talent_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="mainapp.talent",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="talent",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mainapp.user"
            ),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("review_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("rating", models.CharField(max_length=10)),
                ("headline", models.CharField(max_length=50)),
                ("comment", models.CharField(max_length=300)),
                ("review_date", models.DateTimeField(auto_now_add=True)),
                (
                    "systemdate",
                    models.DateTimeField(
                        blank=True, default=datetime.datetime.now, null=True
                    ),
                ),
                (
                    "reviewed_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews_received",
                        to="mainapp.user",
                    ),
                ),
                (
                    "reviewer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews_given",
                        to="mainapp.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PackageInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purchase_date", models.DateTimeField(auto_now_add=True)),
                ("expiry_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unpaid", "Unpaid"),
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=15,
                    ),
                ),
                ("price", models.CharField(max_length=30)),
                ("discount", models.CharField(blank=True, default="0", max_length=30)),
                ("tax", models.CharField(blank=True, default="0", max_length=30)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("credit_card", "Credit Card"),
                            ("paypal", "PayPal"),
                            ("bank_transfer", "Bank Transfer"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "systemdate",
                    models.DateTimeField(
                        blank=True, default=datetime.datetime.now, null=True
                    ),
                ),
                (
                    "package_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainapp.package",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mainapp.user"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="employer",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mainapp.user"
            ),
        ),
        migrations.CreateModel(
            name="Consultation",
            fields=[
                (
                    "consultation_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("topic", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=200)),
                ("consultation_date", models.DateField()),
                (
                    "starting_slot_time",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "ending_slot_time",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("duration_minutes", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=100,
                    ),
                ),
                ("rating", models.CharField(blank=True, max_length=20, null=True)),
                ("price", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "systemdate",
                    models.DateTimeField(
                        blank=True, default=datetime.datetime.now, null=True
                    ),
                ),
                (
                    "consultant_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="mainapp.consultant",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="mainapp.user",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="consultant",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mainapp.user"
            ),
        ),
    ]
