# Generated by Django 5.1.2 on 2024-12-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mainapp",
            "0002_remove_talent_area_consultant_age_consultant_awards_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultant",
            name="education_level",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="consultant",
            name="experience",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="consultant",
            name="language",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="talent",
            name="education_level",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="talent",
            name="experience",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="talent",
            name="language",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
