# Generated by Django 5.1.2 on 2024-12-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0003_alter_consultant_education_level_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consultant",
            name="photo",
        ),
        migrations.RemoveField(
            model_name="employer",
            name="photo",
        ),
        migrations.RemoveField(
            model_name="talent",
            name="photo",
        ),
        migrations.AddField(
            model_name="user",
            name="photo",
            field=models.ImageField(
                blank=True, default="", null=True, upload_to="user/photos/"
            ),
        ),
        migrations.AlterField(
            model_name="consultant",
            name="age",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="talent",
            name="age",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
