# Generated by Django 5.1.2 on 2024-12-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0004_remove_consultant_photo_remove_employer_photo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultant",
            name="language",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="talent",
            name="language",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
