# Generated by Django 5.1.2 on 2025-01-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0006_talent_area"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultant",
            name="province",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="employer",
            name="province",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="talent",
            name="province",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
