# Generated by Django 5.1.2 on 2025-01-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0007_consultant_province_employer_province_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultant",
            name="area",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="consultant",
            name="province",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="employer",
            name="area",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="employer",
            name="city",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="talent",
            name="area",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="talent",
            name="province",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
