# Generated by Django 5.1.2 on 2025-01-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0008_alter_consultant_area_alter_consultant_province_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="ap_deadline",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="total_applicats",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
